name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose pull && docker-compose build
    - name: Run Safety check
      run: docker-compose run app sh -c "safety check"
    - name: Run linter
      run: docker-compose run app sh -c "flake8"