name: Safety Dependency Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install app dependencies
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade safety
    - name: Analysing the code with Safety
      working-directory: ./
      run: safety check
